In [401]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

In [402]:
if torch.backends.mps.is_available():
    mps_device = torch.set_default_device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


# Creating Tensors

In [403]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7, device='mps:0')

In [404]:
scalar.ndim

0

In [405]:
scalar.item() # Get POPO back

7

In [406]:
# Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7], device='mps:0')

In [407]:
vector.ndim # Dimension of the tensor

1

In [408]:
vector.shape # Shape of the tensor

torch.Size([2])

In [409]:
# MATRIX

matrix = torch.tensor(
    [[7, 8],
     [9, 10]]
)
matrix

tensor([[ 7,  8],
        [ 9, 10]], device='mps:0')

In [410]:
matrix.ndim

2

In [411]:
matrix[0]

tensor([7, 8], device='mps:0')

In [412]:
matrix.shape

torch.Size([2, 2])

In [413]:
# TENSOR

tensor = torch.tensor(
    [[[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]]
)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], device='mps:0')

In [414]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='mps:0')

In [415]:
tensor[0, 0]

tensor([1, 2, 3], device='mps:0')

In [416]:
tensor[0, -1]

tensor([7, 8, 9], device='mps:0')

In [417]:
tensor.ndim

3

In [418]:
tensor.shape

torch.Size([1, 3, 3])

## Random Tensors

In [419]:
# Random Tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5880, 0.2433, 0.5797, 0.6805],
        [0.5575, 0.3254, 0.4291, 0.2087],
        [0.0562, 0.2676, 0.1369, 0.5249]], device='mps:0')

In [420]:
random_tensor.ndim

2

In [421]:
random_tensor.shape

torch.Size([3, 4])

In [422]:
random_tensor = torch.rand(1, 3)
random_tensor

tensor([[0.6543, 0.4484, 0.3422]], device='mps:0')

In [423]:
random_tensor = torch.rand(3, 1)
random_tensor

tensor([[0.9979],
        [0.5881],
        [0.8746]], device='mps:0')

In [424]:
random_tensor = torch.rand(3)
random_tensor

tensor([0.0266, 0.3488, 0.8557], device='mps:0')

In [425]:
random_tensor = torch.rand(1)
random_tensor.item()

0.7142608165740967

In [426]:
# Random Tensor with same shape as image tensor
# height, width, colour channels (R, G, B) 
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor

tensor([[[6.5081e-01, 1.3483e-02, 4.0091e-01],
         [7.5908e-01, 6.2280e-01, 3.0647e-01],
         [7.0718e-01, 2.8794e-01, 9.5678e-01],
         ...,
         [2.7218e-01, 4.1125e-01, 5.4225e-01],
         [5.5374e-01, 1.4264e-01, 3.1442e-01],
         [3.9933e-01, 8.2867e-01, 1.6032e-01]],

        [[3.6701e-01, 2.3252e-01, 5.6303e-01],
         [8.9301e-01, 3.8343e-01, 2.6777e-01],
         [2.7210e-01, 4.5447e-01, 2.7387e-01],
         ...,
         [2.6051e-01, 2.8597e-01, 5.1109e-01],
         [7.9585e-01, 5.9987e-01, 1.5737e-01],
         [1.4087e-01, 4.8229e-01, 2.2150e-01]],

        [[2.2679e-02, 9.2896e-01, 2.7301e-01],
         [2.2105e-01, 5.4439e-01, 7.5555e-04],
         [2.7342e-01, 5.9997e-01, 1.6717e-01],
         ...,
         [9.5588e-01, 5.4159e-01, 9.7300e-01],
         [1.8556e-01, 1.4898e-01, 2.8003e-01],
         [9.7155e-01, 5.4521e-01, 1.6405e-02]],

        ...,

        [[7.8175e-01, 3.5803e-02, 5.7587e-01],
         [8.6118e-01, 1.6885e-01, 3.4999e-01]

In [427]:
# Random Tensor of 0 and 1
random_tensor = torch.rand(3, 4)
zeros = torch.zeros(random_tensor[0].shape)
print(random_tensor)
zeros.dot(random_tensor).item()

tensor([[0.8163, 0.9157, 0.7564, 0.8756],
        [0.8721, 0.6721, 0.9948, 0.0559],
        [0.8953, 0.6170, 0.9749, 0.3199]], device='mps:0')


0.0

In [428]:
# Random Tensor of 0 and 1
random_tensor = torch.rand(3, 4)
ones = torch.ones(random_tensor[0].shape)
print(random_tensor)
print(ones.dot(random_tensor)) # sum of all elements
random_tensor.sum()

tensor([[0.5419, 0.4420, 0.3914, 0.5802],
        [0.4462, 0.8912, 0.1805, 0.3882],
        [0.4244, 0.9132, 0.6135, 0.7112]], device='mps:0')
tensor(6.5239, device='mps:0')


tensor(6.5239, device='mps:0')

In [429]:
ones.dtype

torch.float32

In [430]:
zeros.dtype

torch.float32

## Creating tensors from fixed ranges and other tensors

In [431]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='mps:0')

In [432]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924],
       device='mps:0')

In [433]:
# Copy tensor
one_to_ten = torch.arange(start=1, end=11, step=1)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='mps:0')

In [434]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float32_tensor

tensor([3., 6., 9.], device='mps:0')

In [435]:
float32_tensor.dtype

torch.float32

In [436]:
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)

In [437]:
float16_tensor.dtype

torch.float16

In [438]:
int64_tensor = torch.tensor([3, 6, 9], dtype=None)
int64_tensor.dtype

torch.int64

In [439]:
cpu_tensor = torch.tensor([3.0, 6.0, 9.0], device="cpu")
cpu_tensor

tensor([3., 6., 9.])

In [440]:
nograd_tensor = torch.tensor([3.0, 6.0, 9.0], requires_grad=False)
nograd_tensor

tensor([3., 6., 9.], device='mps:0')

# Tensor Datatypes

3 common pitfalls:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [441]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)

In [442]:
float32_tensor + cpu_tensor.to(float32_tensor.device)

tensor([ 6., 12., 18.], device='mps:0')

# Tensor Manipulation

## Tensor Operations

* Addition
* Subtraction
* Element-wise Multiplication
* Matrix Multiplication
* Division

In [443]:
tensor = torch.tensor([1., 2., 3.])
tensor + 10

tensor([11., 12., 13.], device='mps:0')

In [444]:
tensor * 10

tensor([10., 20., 30.], device='mps:0')

In [445]:
tensor * torch.tensor(10)

tensor([10., 20., 30.], device='mps:0')

In [446]:
tensor - 10

tensor([-9., -8., -7.], device='mps:0')

In [447]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000], device='mps:0')

In [448]:
tensor ** 2

tensor([1., 4., 9.], device='mps:0')

In [449]:
torch.mul(tensor, 10)

tensor([10., 20., 30.], device='mps:0')

In [450]:
torch.add(tensor, 10)

tensor([11., 12., 13.], device='mps:0')

In [451]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000], device='mps:0')

In [452]:
torch.pow(tensor, 2)

tensor([1., 4., 9.], device='mps:0')

In [453]:
torch.sub(tensor, 10)

tensor([-9., -8., -7.], device='mps:0')

In [454]:
# Matrix Multiplication

## Element-wise

tensor * tensor

tensor([1., 4., 9.], device='mps:0')

In [455]:
## Dot product
torch.matmul(tensor, tensor)

tensor(14., device='mps:0')

In [456]:
%%timeit

torch.matmul(tensor, tensor)

37.1 µs ± 944 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [457]:
%%timeit

value = 0
for element in tensor:
    value += element * element

298 µs ± 7.07 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [458]:
%%timeit

tensor @ tensor

37.1 µs ± 723 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [459]:
# Matmul of N-DIM tensors

ndim_tensor = torch.matmul(torch.rand(7, 1, 3, 4), torch.rand(5, 4, 7))
# (j x 1 x n x m) @ (k x m x p) -> (j x (k x 1) x [(n x m) @ (m x p)]) = (j x k x n x p)

In [460]:
ndim_tensor.shape
# j x k x n x p

torch.Size([7, 5, 3, 7])

In [461]:
# single dimensional matrices
oneD_1 = torch.tensor([3, 6, 2], dtype=torch.float32)
oneD_2 = torch.tensor([4, 1, 9], dtype=torch.float32)
  
  
# two dimensional matrices
twoD_1 = torch.tensor([[1, 2, 3],
                       [4, 3, 8],
                       [1, 7, 2]], dtype=torch.float32)
twoD_2 = torch.tensor([[2, 4, 1],
                       [1, 3, 6],
                       [2, 6, 5]], dtype=torch.float32)
  
# N-dimensional matrices (N>2)
  
# 2x3x3 dimensional matrix
ND_1 = torch.tensor([[[-0.0135, -0.9197, -0.3395],
                      [-1.0369, -1.3242,  1.4799],
                      [-0.0182, -1.2917,  0.6575]],
  
                     [[-0.3585, -0.0478,  0.4674],
                      [-0.6688, -0.9217, -1.2612],
                      [1.6323, -0.0640,  0.4357]]])
  
# 2x3x4 dimensional matrix
ND_2 = torch.tensor([[[0.2431, -0.1044, -0.1437, -1.4982],
                      [-1.4318, -0.2510,  1.6247,  0.5623],
                      [1.5265, -0.8568, -2.1125, -0.9463]],
  
                     [[0.0182,  0.5207,  1.2890, -1.3232],
                      [-0.2275, -0.8006, -0.6909, -1.0108],
                      [1.3881, -0.0327, -1.4890, -0.5550]]])
  
print("1D matrices output :\n", oneD_1 @ oneD_2)
print("\n2D matrices output :\n", twoD_1 @ twoD_2)
print("\nN-D matrices output :\n", ND_1 @ ND_2) # 2 x 3 x 4
print("\n Mixed matrices output :\n", oneD_1 @ twoD_1 @ twoD_2)

SyntaxError: '(' was never closed (3180762146.py, line 36)

## Tensor Aggregation Operations

In [ ]:
tensor = torch.arange(0., 100., 10)
torch.min(tensor)

In [ ]:
torch.max(tensor)

In [ ]:
torch.sum(tensor)

In [ ]:
tensor.max()

In [ ]:
tensor.min()

In [ ]:
tensor.sum()

In [ ]:
tensor.mean()

In [ ]:
tensor.median()

In [ ]:
tensor.var().sqrt()

In [ ]:
tensor.argmax()

In [ ]:
tensor.argmin()

## Reshaping and Aggregating Tensors

* Reshape -> reshape an input tensor to a given shape
* View -> return a view of a given shape from an input tensor (same memory location)
* Stack -> combine multiple tensors on top of each other (__vstack__) or side by side (__hstack__)
* Squeeze -> remove all `1` dimensions from a tensor
* Unsqueeze -> add a `1` dimension to a tensor
* Permute -> return a view with permuted (swapped) dimensions

In [ ]:
# Tensor Reshaping

x = torch.arange(1., 11.)
x, x.shape

In [ ]:
x_reshaped = x.reshape(10, 1)
x_reshaped

In [ ]:
x_reshaped = x.reshape(5, 2)
x_reshaped

In [ ]:
z = x.view(5, 2)
z

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

In [ ]:
x_unsqueezed = torch.arange(1., 11.).reshape(10, 1)
x_squeezed = torch.squeeze(x_unsqueezed)
x_unsqueezed, x_squeezed, x_squeezed.shape

In [ ]:
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=-1)
x_squeezed, x_unsqueezed, x_unsqueezed.shape

In [ ]:
x_permuted = torch.permute(x_unsqueezed, dims=(1, 0))
x_unsqueezed, x_permuted, x_permuted.shape

In [ ]:
# permute is useful for Computer Vision
image = torch.rand(224, 224, 3)

image_permuted = image.permute(2, 0, 1)

image.shape, image_permuted.shape

## Tensor Access Patterns

In [ ]:
# Indexing

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

In [ ]:
x[0], x[0].shape

In [ ]:
x[:, 0], x[:, 0].shape

In [ ]:
x[0, 0], x[0, 0].shape

In [ ]:
x[0, 0, 0]

In [ ]:
x[0, 0, 1]

In [ ]:
x[0, 1, 0]

In [ ]:
x[:, 0, :]

In [ ]:
x[:, :, 0]

## Interacting with NumPy

In [ ]:
# From NumPy

array = np.arange(1., 8.)
tensor = torch.from_numpy(array)

# .from_numpy will convert to float64!
# array and tensor SHARE MEMORY!

array, array.shape, tensor, tensor.shape

In [ ]:
array += 10

array, tensor

In [ ]:
tensor -= 10

array, tensor

In [ ]:
# To NumPy

tensor = torch.ones(7)
numpy_tensor = tensor.cpu().numpy()

# If the tensor is on GPU, call .cpu() before .numpy()
# .numpy will convert to float32!

tensor, tensor.shape, numpy_tensor, numpy_tensor.shape

# Reproducibility in PyTorch

In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

In [ ]:
torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(3, 4)
random_tensor_C = torch.rand(3, 4)


torch.manual_seed(RANDOM_SEED)

random_tensor_B = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)


random_tensor_A == random_tensor_B, random_tensor_C == random_tensor_D

# PyTorch on GPU

In [ ]:
# Check for GPU access

torch.cuda.is_available(), torch.backends.cuda.is_built()

In [ ]:
torch.backends.mps.is_available(), torch.backends.mps.is_built()

In [ ]:
torch.backends.cudnn.is_available()

In [ ]:
# Device Agnostic Code

DEVICE = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"

DEVICE

In [ ]:
# Count number of CUDA GPUs

torch.cuda.device_count()

In [ ]:
# Putting tensors and models on the GPU

tensor = torch.tensor([1, 2, 3], device="cpu")

tensor, tensor.device

In [ ]:
# Move to GPU if available

tensor_on_gpu = tensor.to(DEVICE)

tensor_on_gpu, tensor_on_gpu.device

In [ ]:
# Back to CPU

tensor_on_gpu.cpu().numpy()