In [569]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

In [570]:
if torch.backends.mps.is_available():
    mps_device = torch.set_default_device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


# Creating Tensors

In [571]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7, device='mps:0')

In [572]:
scalar.ndim

0

In [573]:
scalar.item() # Get POPO back

7

In [574]:
# Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7], device='mps:0')

In [575]:
vector.ndim # Dimension of the tensor

1

In [576]:
vector.shape # Shape of the tensor

torch.Size([2])

In [577]:
# MATRIX

matrix = torch.tensor(
    [[7, 8],
     [9, 10]]
)
matrix

tensor([[ 7,  8],
        [ 9, 10]], device='mps:0')

In [578]:
matrix.ndim

2

In [579]:
matrix[0]

tensor([7, 8], device='mps:0')

In [580]:
matrix.shape

torch.Size([2, 2])

In [581]:
# TENSOR

tensor = torch.tensor(
    [[[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]]
)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], device='mps:0')

In [582]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='mps:0')

In [583]:
tensor[0, 0]

tensor([1, 2, 3], device='mps:0')

In [584]:
tensor[0, -1]

tensor([7, 8, 9], device='mps:0')

In [585]:
tensor.ndim

3

In [586]:
tensor.shape

torch.Size([1, 3, 3])

## Random Tensors

In [587]:
# Random Tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5880, 0.2433, 0.5797, 0.6805],
        [0.5575, 0.3254, 0.4291, 0.2087],
        [0.0562, 0.2676, 0.1369, 0.5249]], device='mps:0')

In [588]:
random_tensor.ndim

2

In [589]:
random_tensor.shape

torch.Size([3, 4])

In [590]:
random_tensor = torch.rand(1, 3)
random_tensor

tensor([[0.6543, 0.4484, 0.3422]], device='mps:0')

In [591]:
random_tensor = torch.rand(3, 1)
random_tensor

tensor([[0.9979],
        [0.5881],
        [0.8746]], device='mps:0')

In [592]:
random_tensor = torch.rand(3)
random_tensor

tensor([0.0266, 0.3488, 0.8557], device='mps:0')

In [593]:
random_tensor = torch.rand(1)
random_tensor.item()

0.7142608165740967

In [594]:
# Random Tensor with same shape as image tensor
# height, width, colour channels (R, G, B) 
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor

tensor([[[6.5081e-01, 1.3483e-02, 4.0091e-01],
         [7.5908e-01, 6.2280e-01, 3.0647e-01],
         [7.0718e-01, 2.8794e-01, 9.5678e-01],
         ...,
         [2.7218e-01, 4.1125e-01, 5.4225e-01],
         [5.5374e-01, 1.4264e-01, 3.1442e-01],
         [3.9933e-01, 8.2867e-01, 1.6032e-01]],

        [[3.6701e-01, 2.3252e-01, 5.6303e-01],
         [8.9301e-01, 3.8343e-01, 2.6777e-01],
         [2.7210e-01, 4.5447e-01, 2.7387e-01],
         ...,
         [2.6051e-01, 2.8597e-01, 5.1109e-01],
         [7.9585e-01, 5.9987e-01, 1.5737e-01],
         [1.4087e-01, 4.8229e-01, 2.2150e-01]],

        [[2.2679e-02, 9.2896e-01, 2.7301e-01],
         [2.2105e-01, 5.4439e-01, 7.5555e-04],
         [2.7342e-01, 5.9997e-01, 1.6717e-01],
         ...,
         [9.5588e-01, 5.4159e-01, 9.7300e-01],
         [1.8556e-01, 1.4898e-01, 2.8003e-01],
         [9.7155e-01, 5.4521e-01, 1.6405e-02]],

        ...,

        [[7.8175e-01, 3.5803e-02, 5.7587e-01],
         [8.6118e-01, 1.6885e-01, 3.4999e-01]

In [595]:
# Random Tensor of 0 and 1
random_tensor = torch.rand(3, 4)
zeros = torch.zeros(random_tensor[0].shape)
print(random_tensor)
zeros.dot(random_tensor).item()

tensor([[0.8163, 0.9157, 0.7564, 0.8756],
        [0.8721, 0.6721, 0.9948, 0.0559],
        [0.8953, 0.6170, 0.9749, 0.3199]], device='mps:0')


0.0

In [596]:
# Random Tensor of 0 and 1
random_tensor = torch.rand(3, 4)
ones = torch.ones(random_tensor[0].shape)
print(random_tensor)
print(ones.dot(random_tensor)) # sum of all elements
random_tensor.sum()

tensor([[0.5419, 0.4420, 0.3914, 0.5802],
        [0.4462, 0.8912, 0.1805, 0.3882],
        [0.4244, 0.9132, 0.6135, 0.7112]], device='mps:0')
tensor(6.5239, device='mps:0')


tensor(6.5239, device='mps:0')

In [597]:
ones.dtype

torch.float32

In [598]:
zeros.dtype

torch.float32

## Creating tensors from fixed ranges and other tensors

In [599]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='mps:0')

In [600]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924],
       device='mps:0')

In [601]:
# Copy tensor
one_to_ten = torch.arange(start=1, end=11, step=1)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='mps:0')

In [602]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float32_tensor

tensor([3., 6., 9.], device='mps:0')

In [603]:
float32_tensor.dtype

torch.float32

In [604]:
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)

In [605]:
float16_tensor.dtype

torch.float16

In [606]:
int64_tensor = torch.tensor([3, 6, 9], dtype=None)
int64_tensor.dtype

torch.int64

In [607]:
cpu_tensor = torch.tensor([3.0, 6.0, 9.0], device="cpu")
cpu_tensor

tensor([3., 6., 9.])

In [608]:
nograd_tensor = torch.tensor([3.0, 6.0, 9.0], requires_grad=False)
nograd_tensor

tensor([3., 6., 9.], device='mps:0')

# Tensor Datatypes

3 common pitfalls:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [609]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)

In [610]:
float32_tensor + cpu_tensor.to(float32_tensor.device)

tensor([ 6., 12., 18.], device='mps:0')

# Tensor Manipulation

## Tensor Operations

* Addition
* Subtraction
* Element-wise Multiplication
* Matrix Multiplication
* Division

In [611]:
tensor = torch.tensor([1., 2., 3.])
tensor + 10

tensor([11., 12., 13.], device='mps:0')

In [612]:
tensor * 10

tensor([10., 20., 30.], device='mps:0')

In [613]:
tensor * torch.tensor(10)

tensor([10., 20., 30.], device='mps:0')

In [614]:
tensor - 10

tensor([-9., -8., -7.], device='mps:0')

In [615]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000], device='mps:0')

In [616]:
tensor ** 2

tensor([1., 4., 9.], device='mps:0')

In [617]:
torch.mul(tensor, 10)

tensor([10., 20., 30.], device='mps:0')

In [618]:
torch.add(tensor, 10)

tensor([11., 12., 13.], device='mps:0')

In [619]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000], device='mps:0')

In [620]:
torch.pow(tensor, 2)

tensor([1., 4., 9.], device='mps:0')

In [621]:
torch.sub(tensor, 10)

tensor([-9., -8., -7.], device='mps:0')

In [622]:
# Matrix Multiplication

## Element-wise

tensor * tensor

tensor([1., 4., 9.], device='mps:0')

In [623]:
## Dot product
torch.matmul(tensor, tensor)

tensor(14., device='mps:0')

In [624]:
%%timeit

torch.matmul(tensor, tensor)

36.9 µs ± 669 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [625]:
%%timeit

value = 0
for element in tensor:
    value += element * element

281 µs ± 1.29 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [626]:
%%timeit

tensor @ tensor

37 µs ± 338 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [627]:
# Matmul of N-DIM tensors

ndim_tensor = torch.matmul(torch.rand(7, 1, 3, 4), torch.rand(5, 4, 7))
# (j x 1 x n x m) @ (k x m x p) -> (j x (k x 1) x [(n x m) @ (m x p)]) = (j x k x n x p)

In [628]:
ndim_tensor.shape
# j x k x n x p

torch.Size([7, 5, 3, 7])

In [629]:
# single dimensional matrices
oneD_1 = torch.tensor([3, 6, 2], dtype=torch.float32)
oneD_2 = torch.tensor([4, 1, 9], dtype=torch.float32)
  
  
# two dimensional matrices
twoD_1 = torch.tensor([[1, 2, 3],
                       [4, 3, 8],
                       [1, 7, 2]], dtype=torch.float32)
twoD_2 = torch.tensor([[2, 4, 1],
                       [1, 3, 6],
                       [2, 6, 5]], dtype=torch.float32)
  
# N-dimensional matrices (N>2)
  
# 2x3x3 dimensional matrix
ND_1 = torch.tensor([[[-0.0135, -0.9197, -0.3395],
                      [-1.0369, -1.3242,  1.4799],
                      [-0.0182, -1.2917,  0.6575]],
  
                     [[-0.3585, -0.0478,  0.4674],
                      [-0.6688, -0.9217, -1.2612],
                      [1.6323, -0.0640,  0.4357]]])
  
# 2x3x4 dimensional matrix
ND_2 = torch.tensor([[[0.2431, -0.1044, -0.1437, -1.4982],
                      [-1.4318, -0.2510,  1.6247,  0.5623],
                      [1.5265, -0.8568, -2.1125, -0.9463]],
  
                     [[0.0182,  0.5207,  1.2890, -1.3232],
                      [-0.2275, -0.8006, -0.6909, -1.0108],
                      [1.3881, -0.0327, -1.4890, -0.5550]]])
  
print("1D matrices output :\n", oneD_1 @ oneD_2)
print("\n2D matrices output :\n", twoD_1 @ twoD_2)
print("\nN-D matrices output :\n", ND_1 @ ND_2) # 2 x 3 x 4
print("\n Mixed matrices output :\n", oneD_1 @ twoD_1 @ twoD_2)

1D matrices output :
 tensor(36., device='mps:0')

2D matrices output :
 tensor([[10., 28., 28.],
        [27., 73., 62.],
        [13., 37., 53.]], device='mps:0')

N-D matrices output :
 tensor([[[ 0.7953,  0.5231, -0.7751, -0.1757],
         [ 3.9030, -0.8274, -5.1287, -0.5915],
         [ 2.8487, -0.2372, -3.4850, -1.3212]],

        [[ 0.6531, -0.1637, -1.1250,  0.2633],
         [-1.5532,  0.4309,  1.6526,  2.5166],
         [ 0.6491,  0.8869,  1.4995, -2.3370]]], device='mps:0')

 Mixed matrices output :
 tensor([218., 596., 562.], device='mps:0')


## Tensor Aggregation Operations

In [630]:
tensor = torch.arange(0., 100., 10)
torch.min(tensor)

tensor(0., device='mps:0')

In [631]:
torch.max(tensor)

tensor(90., device='mps:0')

In [632]:
torch.sum(tensor)

tensor(450., device='mps:0')

In [633]:
tensor.max()

tensor(90., device='mps:0')

In [634]:
tensor.min()

tensor(0., device='mps:0')

In [635]:
tensor.sum()

tensor(450., device='mps:0')

In [636]:
tensor.mean()

tensor(45., device='mps:0')

In [637]:
tensor.median()

tensor(40., device='mps:0')

In [638]:
tensor.var().sqrt()

tensor(30.2765, device='mps:0')

In [639]:
tensor.argmax()

tensor(9, device='mps:0')

In [640]:
tensor.argmin()

tensor(0, device='mps:0')

## Reshaping and Aggregating Tensors

* Reshape -> reshape an input tensor to a given shape
* View -> return a view of a given shape from an input tensor (same memory location)
* Stack -> combine multiple tensors on top of each other (__vstack__) or side by side (__hstack__)
* Squeeze -> remove all `1` dimensions from a tensor
* Unsqueeze -> add a `1` dimension to a tensor
* Permute -> return a view with permuted (swapped) dimensions

In [641]:
# Tensor Reshaping

x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], device='mps:0'),
 torch.Size([10]))

In [642]:
x_reshaped = x.reshape(10, 1)
x_reshaped

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]], device='mps:0')

In [643]:
x_reshaped = x.reshape(5, 2)
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]], device='mps:0')

In [644]:
z = x.view(5, 2)
z

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]], device='mps:0')

In [645]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]], device='mps:0'),
 torch.Size([10, 4]))

In [646]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]], device='mps:0'),
 torch.Size([4, 10]))

In [647]:
x_unsqueezed = torch.arange(1., 11.).reshape(10, 1)
x_squeezed = torch.squeeze(x_unsqueezed)
x_unsqueezed, x_squeezed, x_squeezed.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]], device='mps:0'),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], device='mps:0'),
 torch.Size([10]))

In [648]:
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=-1)
x_squeezed, x_unsqueezed, x_unsqueezed.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], device='mps:0'),
 tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]], device='mps:0'),
 torch.Size([10, 1]))

In [649]:
x_permuted = torch.permute(x_unsqueezed, dims=(1, 0))
x_unsqueezed, x_permuted, x_permuted.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]], device='mps:0'),
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]], device='mps:0'),
 torch.Size([1, 10]))

In [650]:
# permute is useful for Computer Vision
image = torch.rand(224, 224, 3)

image_permuted = image.permute(2, 0, 1)

image.shape, image_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Tensor Access Patterns

In [651]:
# Indexing

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]], device='mps:0'),
 torch.Size([1, 3, 3]))

In [652]:
x[0], x[0].shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]], device='mps:0'),
 torch.Size([3, 3]))

In [653]:
x[:, 0], x[:, 0].shape

(tensor([[1, 2, 3]], device='mps:0'), torch.Size([1, 3]))

In [654]:
x[0, 0], x[0, 0].shape

(tensor([1, 2, 3], device='mps:0'), torch.Size([3]))

In [655]:
x[0, 0, 0]

tensor(1, device='mps:0')

In [656]:
x[0, 0, 1]

tensor(2, device='mps:0')

In [657]:
x[0, 1, 0]

tensor(4, device='mps:0')

In [658]:
x[:, 0, :]

tensor([[1, 2, 3]], device='mps:0')

In [659]:
x[:, :, 0]

tensor([[1, 4, 7]], device='mps:0')

## Interacting with NumPy

In [660]:
# From NumPy

array = np.arange(1., 8.)
tensor = torch.from_numpy(array)

# .from_numpy will convert to float64!
# array and tensor SHARE MEMORY!

array, array.shape, tensor, tensor.shape

(array([1., 2., 3., 4., 5., 6., 7.]),
 (7,),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.Size([7]))

In [661]:
array += 10

array, tensor

(array([11., 12., 13., 14., 15., 16., 17.]),
 tensor([11., 12., 13., 14., 15., 16., 17.], dtype=torch.float64))

In [662]:
tensor -= 10

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [663]:
# To NumPy

tensor = torch.ones(7)
numpy_tensor = tensor.cpu().numpy()

# If the tensor is on GPU, call .cpu() before .numpy()
# .numpy will convert to float32!

tensor, tensor.shape, numpy_tensor, numpy_tensor.shape

(tensor([1., 1., 1., 1., 1., 1., 1.], device='mps:0'),
 torch.Size([7]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 (7,))

# Reproducibility in PyTorch

In [664]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[8.1718e-01, 5.8811e-01, 5.5805e-01, 7.6914e-01],
         [3.3936e-01, 4.5596e-01, 6.7508e-01, 4.4060e-04],
         [4.0876e-01, 1.7912e-01, 5.9732e-01, 8.4722e-01]], device='mps:0'),
 tensor([[0.0661, 0.3270, 0.5155, 0.2259],
         [0.8333, 0.5891, 0.2452, 0.5659],
         [0.4646, 0.4861, 0.5399, 0.6836]], device='mps:0'),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]], device='mps:0'))

In [665]:
torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(3, 4)
random_tensor_C = torch.rand(3, 4)


torch.manual_seed(RANDOM_SEED)

random_tensor_B = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)


random_tensor_A == random_tensor_B, random_tensor_C == random_tensor_D

(tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]], device='mps:0'),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]], device='mps:0'))

# PyTorch on GPU

In [666]:
# Check for GPU access

torch.cuda.is_available(), torch.backends.cuda.is_built()

(False, False)

In [667]:
torch.backends.mps.is_available(), torch.backends.mps.is_built()

(True, True)

In [668]:
torch.backends.cudnn.is_available()

False

In [669]:
# Device Agnostic Code

DEVICE = "cuda" if torch.cuda.is_available() \
    else "mps" if torch.backends.mps.is_available() \
    else "cpu"

DEVICE

'mps'

In [670]:
# Count number of CUDA GPUs

torch.cuda.device_count()

0

In [671]:
# Putting tensors and models on the GPU

tensor = torch.tensor([1, 2, 3], device="cpu")

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [672]:
# Move to GPU if available

tensor_on_gpu = tensor.to(DEVICE)

tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='mps:0'), device(type='mps', index=0))

In [673]:
# Back to CPU

tensor_on_gpu.cpu().numpy()

array([1, 2, 3])