In [1]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

In [2]:
if torch.backends.mps.is_available():
    mps_device = torch.set_default_device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


# Creating Tensors

In [3]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7, device='mps:0')

In [4]:
scalar.ndim

0

In [5]:
scalar.item() # Get POPO back

7

In [6]:
# Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7], device='mps:0')

In [7]:
vector.ndim # Dimension of the tensor

1

In [8]:
vector.shape # Shape of the tensor

torch.Size([2])

In [9]:
# MATRIX

matrix = torch.tensor(
    [[7, 8],
     [9, 10]]
)
matrix

tensor([[ 7,  8],
        [ 9, 10]], device='mps:0')

In [10]:
matrix.ndim

2

In [11]:
matrix[0]

tensor([7, 8], device='mps:0')

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# TENSOR

tensor = torch.tensor(
    [[[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]]
)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], device='mps:0')

In [14]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='mps:0')

In [15]:
tensor[0, 0]

tensor([1, 2, 3], device='mps:0')

In [16]:
tensor[0, -1]

tensor([7, 8, 9], device='mps:0')

In [17]:
tensor.ndim

3

In [18]:
tensor.shape

torch.Size([1, 3, 3])

## Random Tensors

In [19]:
# Random Tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2973, 0.1214, 0.7248, 0.1033],
        [0.4436, 0.9827, 0.0942, 0.5960],
        [0.5202, 0.4889, 0.5998, 0.9141]], device='mps:0')

In [20]:
random_tensor.ndim

2

In [21]:
random_tensor.shape

torch.Size([3, 4])

In [22]:
random_tensor = torch.rand(1, 3)
random_tensor

tensor([[0.4836, 0.8226, 0.1681]], device='mps:0')

In [23]:
random_tensor = torch.rand(3, 1)
random_tensor

tensor([[0.6563],
        [0.7312],
        [0.4109]], device='mps:0')

In [24]:
random_tensor = torch.rand(3)
random_tensor

tensor([0.5581, 0.9227, 0.2220], device='mps:0')

In [25]:
random_tensor = torch.rand(1)
random_tensor.item()

0.21429908275604248

In [26]:
# Random Tensor with same shape as image tensor
# height, width, colour channels (R, G, B) 
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor

tensor([[[0.5273, 0.0863, 0.4093],
         [0.2303, 0.9501, 0.1870],
         [0.7886, 0.1741, 0.2432],
         ...,
         [0.7245, 0.4280, 0.4122],
         [0.4714, 0.0220, 0.3422],
         [0.6306, 0.1989, 0.5046]],

        [[0.6154, 0.6321, 0.3663],
         [0.6663, 0.5526, 0.9389],
         [0.3569, 0.0571, 0.9174],
         ...,
         [0.0394, 0.9728, 0.4387],
         [0.4891, 0.0613, 0.0636],
         [0.4327, 0.2086, 0.6891]],

        [[0.1396, 0.2237, 0.0089],
         [0.8087, 0.1457, 0.8420],
         [0.0551, 0.7710, 0.3737],
         ...,
         [0.5431, 0.4332, 0.2921],
         [0.6126, 0.0134, 0.2872],
         [0.1630, 0.1714, 0.9649]],

        ...,

        [[0.3359, 0.6838, 0.0818],
         [0.5309, 0.1656, 0.7350],
         [0.0241, 0.6356, 0.5833],
         ...,
         [0.8642, 0.3399, 0.6847],
         [0.0223, 0.7935, 0.7336],
         [0.5464, 0.0171, 0.8736]],

        [[0.0516, 0.4063, 0.9404],
         [0.2830, 0.2947, 0.0916],
         [0.

In [27]:
# Random Tensor of 0 and 1
random_tensor = torch.rand(3, 4)
zeros = torch.zeros(random_tensor[0].shape)
print(random_tensor)
zeros.dot(random_tensor).item()

tensor([[0.5238, 0.0114, 0.9500, 0.3763],
        [0.6265, 0.1563, 0.9671, 0.7432],
        [0.8034, 0.8123, 0.7619, 0.2116]], device='mps:0')


0.0

In [28]:
# Random Tensor of 0 and 1
random_tensor = torch.rand(3, 4)
ones = torch.ones(random_tensor[0].shape)
print(random_tensor)
print(ones.dot(random_tensor)) # sum of all elements
random_tensor.sum()

tensor([[0.0014, 0.9440, 0.8950, 0.4450],
        [0.2807, 0.1296, 0.8160, 0.8143],
        [0.7278, 0.7183, 0.1520, 0.8670]], device='mps:0')
tensor(6.7909, device='mps:0')


tensor(6.7909, device='mps:0')

In [29]:
ones.dtype

torch.float32

In [30]:
zeros.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [31]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='mps:0')

In [32]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924],
       device='mps:0')

In [33]:
# Copy tensor
one_to_ten = torch.arange(start=1, end=11, step=1)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='mps:0')

In [34]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float32_tensor

tensor([3., 6., 9.], device='mps:0')

In [35]:
float32_tensor.dtype

torch.float32

In [36]:
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)

In [37]:
float16_tensor.dtype

torch.float16

In [38]:
int64_tensor = torch.tensor([3, 6, 9], dtype=None)
int64_tensor.dtype

torch.int64

In [39]:
cpu_tensor = torch.tensor([3.0, 6.0, 9.0], device="cpu")
cpu_tensor

tensor([3., 6., 9.])

In [40]:
nograd_tensor = torch.tensor([3.0, 6.0, 9.0], requires_grad=False)
nograd_tensor

tensor([3., 6., 9.], device='mps:0')

# Tensor Datatypes

3 common pitfalls:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [41]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)

In [42]:
float32_tensor + cpu_tensor.to(float32_tensor.device)

tensor([ 6., 12., 18.], device='mps:0')

# Tensor Manipulation

## Tensor Operations

* Addition
* Subtraction
* Element-wise Multiplication
* Matrix Multiplication
* Division

In [57]:
tensor = torch.tensor([1., 2., 3.])
tensor + 10

tensor([11., 12., 13.], device='mps:0')

In [44]:
tensor * 10

tensor([10., 20., 30.], device='mps:0')

In [45]:
tensor * torch.tensor(10)

tensor([10., 20., 30.], device='mps:0')

In [46]:
tensor - 10

tensor([-9., -8., -7.], device='mps:0')

In [47]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000], device='mps:0')

In [48]:
tensor ** 2

tensor([1., 4., 9.], device='mps:0')

In [49]:
torch.mul(tensor, 10)

tensor([10., 20., 30.], device='mps:0')

In [50]:
torch.add(tensor, 10)

tensor([11., 12., 13.], device='mps:0')

In [51]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000], device='mps:0')

In [52]:
torch.pow(tensor, 2)

tensor([1., 4., 9.], device='mps:0')

In [54]:
torch.sub(tensor, 10)

tensor([-9., -8., -7.], device='mps:0')

In [55]:
# Matrix Multiplication

## Element-wise

tensor * tensor

tensor([1., 4., 9.], device='mps:0')

In [56]:
## Dot product
torch.matmul(tensor, tensor)

tensor(14., device='mps:0')

In [115]:
%%timeit

torch.matmul(tensor, tensor)

36.4 µs ± 69.7 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [144]:
%%timeit

value = 0
for element in tensor:
    value += element * element

279 µs ± 2.45 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [117]:
%%timeit

tensor @ tensor

36.7 µs ± 166 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [141]:
# Matmul of N-DIM tensors

ndim_tensor = torch.rand(4, 1, 3, 2) @ torch.rand(5, 2, 6)

In [143]:
ndim_tensor.shape

torch.Size([4, 5, 3, 6])